Fix udp_socket test build issue on arm64.
The SIOCGSTAMP macro was missing on some arm64 platform which
will result in build errors:
test/syscalls/linux/udp_socket_test_cases.cc:1263:25: error:
'SIOCGSTAMP' was not declared in this scope
   ASSERT_THAT(ioctl(s_, SIOCGSTAMP, &tv),
SyscallFailsWithErrno(ENOENT));

Signed-off-by: Haibo Xu <haibo.xu@arm.com>
Change-Id: I894655f55282308012d64afd54c88dabc014cada