Support nvmlDeviceGetComputeRunningProcesses_ in nvproxy to fix PyTorch OOM handling
### What

Implement **`NV0080_CTRL_CMD_GPU_GET_CLASSLIST`** and **`NV2080_CTRL_CMD_GPU_GET_PIDS`** and **`NV2080_CTRL_CMD_GPU_GET_PID_INFO`** to fix OOM handling in PyTorch.

Currently `runsc`  breaks PyTorch's OOM reporting functionality. An OOM should output, and does output on `runc`, an exception like this:

```
Traceback (most recent call last):
  File "../../repro.py", line 7, in <module>
    M = torch.rand((n, n)).to(torch.device("cuda"))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.63 GiB. GPU 0 has a total capacty of 14.61 GiB of which 14.51 GiB is free. Process 46000 has 100.00 MiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

but in `runsc` you get:

```
Traceback (most recent call last):
  File "../../repro.py", line 7, in <module>
    M = torch.rand((n, n)).to(torch.device("cuda"))
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch.
```

### Why

PyTorch's OOM handling currently bears out in a few unimplemented control commands, `800201` and `2080018d`, and `2080018e`.

```
# sniffer output
426: 0 =  10(      /dev/nvidiactl) 0x 20 NV_ESC_RM_CONTROL client: c1d0003c object: a55a0020 cmd:   800201 NV0080_CTRL_CMD_GPU_GET_CLASSLIST params: 0x7ffdf07d2570 0x10 flags: 0 status 0x0
427: 0 =  10(      /dev/nvidiactl) 0x 20 NV_ESC_RM_CONTROL client: c1d0003c object: a55a0020 cmd:   800201 NV0080_CTRL_CMD_GPU_GET_CLASSLIST params: 0x7ffdf07d2570 0x10 flags: 0 status 0x0
428: 0 =  10(      /dev/nvidiactl) 0x 20 NV_ESC_RM_CONTROL client: c1d0003c object: a55a0030 cmd: 2080018d UNKNOWN params: 0x7ffdf07cdee0 0xee4 flags: 0 status 0x0
429: 0 =  10(      /dev/nvidiactl) 0x 20 NV_ESC_RM_CONTROL client: c1d0003c object: a55a0030 cmd: 2080018e UNKNOWN params: 0x7ffdf07cedd0 0x3848 flags: 0 status 0x0
```

These are called here, https://github.com/pytorch/pytorch/blob/release/2.1/c10/cuda/CUDACachingAllocator.cpp#L1147, at an invocation of `nvmlDeviceGetComputeRunningProcesses_`.

This problem with `nvmlDeviceGetComputeRunningProcesses_` is reproducible outside PyTorch with a separate Python script, `repro_2.py` included in the reproduction Docker image.

### Steps to reproduce

These reproduction steps were run on a custom AMI built on Ubuntu 20.04. The AWS instance type is `g4dn.2xlarge`

**1. Install gvisor**

```bash
URL="https://storage.googleapis.com/gvisor/releases/master/latest/${ARCH}"
wget -nc "${URL}/runsc" "${URL}/runsc.sha512"
chmod +x runsc
sudo cp runsc /usr/local/bin/runsc
sudo /usr/local/bin/runsc install
sudo systemctl reload docker
```

**2. Add GPU enabling gvisor options**

In `/etc/docker/daemon.json`:

```json
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        },
        "runsc": {
            "path": "/usr/local/bin/runsc",
	    "runtimeArgs": ["--nvproxy", "--nvproxy-docker", "-debug-log=/tmp/runsc/", "-debug", "-strace"]

        }
    }
}
```

then run `sudo systemctl reload docker`

**3. Run the reproducing PyTorch application**

```Dockerfile
FROM nvidia/cuda:12.2.0-devel-ubuntu20.04

RUN apt-get update && apt-get install --yes python3 python3-distutils clang wget vim
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN python3 -m pip install clang~=10.0.1 # must match version of `clang` installed above.
RUN python3 -m pip install torch numpy pynvml

# This will OOM, and should show PyTorch's OOM report output.
COPY <<EOF repro.py
import torch
print(torch.__version__)
torch.set_default_dtype(torch.float64)
n = 50_000
print(f"matrix size: {n} x {n}")
assert torch.cuda.is_available(), "cuda not available"
M = torch.rand((n, n)).to(torch.device("cuda"))
N = torch.linalg.inv(M)
I = torch.eye(n).to(torch.device("cuda"))
R = torch.matmul(M, N) - I
threshold = 0.5
mean = torch.mean(torch.abs(R))
print(mean)
assert mean < threshold, f"Mean of matrix {mean} exceeded thresold of {threshold}."
EOF

# Isolates the above repro's issue to a single
# NVML API call, currently unimplemented in gVisor
COPY <<EOF repro_2.py
import pynvml

pynvml.nvmlInit()

deviceCount = pynvml.nvmlDeviceGetCount()
for device_id in range(deviceCount):
    handle = pynvml.nvmlDeviceGetHandleByIndex(device_id)
    cps = pynvml.nvmlDeviceGetComputeRunningProcesses(handle)
    print(cps)
EOF

ENTRYPOINT ["python3", "repro.py"]
```

then

```bash
docker build . -f Dockerfile -t repro-oom
```

This program will OOM, and the behavior is as described at the top of this description box.

### runsc version

```shell
runsc version release-20230710.0-22-gf5049f6885ca
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:57 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:50:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Whereas with just the default Docker runtime:

```
ubuntu@ip-172-31-73-139:~$ sudo docker run --gpus all repro-illegal-mem-access
2.0.1+cu117
matrix size: 4993 x 4993
tensor(1.9216e-12, device='cuda:0')
```

### uname

`Linux ip-172-31-73-139 5.13.0-1029-aws #32~20.04.1-Ubuntu SMP Thu Jun 9 13:03:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/google/gvisor/pull/9700 from thundergolfer:master f8ee47b91d6c36862ecbc0b5be9ac8528a292cec
PiperOrigin-RevId: 583075987